services:
  client:
    image: keuzewijzer-client:${ENV_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${ENV_PORT}:80
      - ${ENV_PORT_SSL}:443
    networks:
      - container_network

networks:
  container_network:
    name: ${ENV_KEY}_network
    external: false
