services:
  client:
    image: keuzewijzer-client:${ENV_KEY}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
        ENV: ${ENV_KEY}
        AZURE_AD_REDIRECT_URI: ${AZURE_AD_REDIRECT_URI}
    ports:
      - ${ENV_PORT}:80
      - ${ENV_PORT_SSL}:443
    networks:
      - container_network

networks:
  container_network:
    name: ${ENV_KEY}_network
    external: true
