services:
  client:
    image: keuzewijzer-client:${ENV_KEY}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${API_URL}
        ENV: ${ENV_KEY}
    ports:
      - ${ENV_PORT}:80
      - ${ENV_PORT_SSL}:443
    environment:
      CYPRESS_BASE_URL: http://localhost:${ENV_PORT_SSL}
    networks:
      - container_network

networks:
  container_network:
    name: ${ENV_KEY}_network
    external: true
