services:
  client:
    image: keuzewijzer-client:developments
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - container_network

networks:
  container_network:
    name: developments_network
    driver: bridge
