name: Cypress E2E tests
on:
  push:
    branches:
      - development
      
jobs:
  RunE2E:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Cypress docker container with local tests
      run: |
        docker rm --force cypress-test
        docker pull cypress/included:13.9.0
        docker run --name cypress-test -v ./cypress/e2e:/e2e -v ./cypress.config.js:/cypress.config.js -w /e2e cypress/included:13.9.0
      env:
        CYPRESS_BASE_URL: '${{ vars.CYPRESS_BASE_URL }}'
